using System;
using System.Collections.Generic;

namespace DE_Portal.DAL.Models.KW4
{
    public partial class CheckPoint
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string Service { get; set; }
        public string Monitoring { get; set; }
        public int OwnerId { get; set; }
        public int? CrawlerId { get; set; }
        public DateTime? Review { get; set; }
        public DateTime CreatingTime { get; set; }
        public bool? Broken { get; set; }
        public string Frequency { get; set; }
        public bool Autogenerated { get; set; }
        public string Schedule { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? GenerateTime { get; set; }
        public bool Deleted { get; set; }
    }
}
